name: "Build native"
on:
  workflow_dispatch: ~
  push:
    paths:
      - "**.java"
      - "**.sh"
      - "**MAKEFILE*"
      - "**.gradle"
      - "**.properties"
      - "**.c"
      - "**.h"
    branches:
      - "master"
      - "development"
      - "ci"
  pull_request:
    paths:
      - "**.java"
      - "**.sh"
      - "**MAKEFILE*"
      - "**.gradle"
      - "**.properties"
      - "**.c"
      - "**.h"
    types:
      - opened
      - synchronize
      - reopened
jobs:
  BUILD-LIB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      # Use the v1 of this action
      - uses: mbround18/setup-osxcross@v1
        # This builds executables & sets env variables for rust to consume.
        with:
          osx-version: "13.1"
      - name: Set up MinGW x64
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Install dependencies
        run: sudo apt install gcc-multilib
      - name: Install arm cross compilers
        run: sudo apt install crossbuild-essential-arm64 binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi
      - name: Build native
        run: native/shared-build-setup.sh 5.3 22.2
      - name: Upload native
        uses: actions/upload-artifact@v3
        with:
          name: native libs
          path: native-*/libjnlua-5.3-*
      - name: Prepare native
        run: native/prepare-java.sh 5.3
      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build java
        run: ./gradlew && ./gradlew build
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: JNLua
          path: build/libs/JNLua_GC-*.jar

